=head1 jperms.pl

recursively set permissions and ownerships according to pattern rules

=head1 OPTIONS

jperms.pl [options] [dir ...]

 Options:
   -help|-h|-?     help
   -man            full documentation
   -dir            directory to descend
   -file           patterns file
   -no_run         don't run any commands
   -verbosity      repeat to increase

=head1 DESCRIPTION

jperms.pl descends the specified directory tree applying permissions and
ownerships to each file or directory found according to a set
of pattern rules.

=head1 RULES

Pattern rules are specified as a list of lines.
Each line consists of 5 fields separated by whitespace:

 # pattern   owner   group   dir_mode   file_mode

- pattern is a regex (NOT a fileglob!) to be matched against each path
found during the tree descent.

- Patterns are automatically surrounded by ^ and $ when matching, meaning
that it must match the whole of the current path (not just part of it).

- file paths include the top level path exactly as specified on the command
line, so a pattern to match a *relative* top level directory (e.g.  "./dir")
must also match the dot (".") at the start of each path (e.g. "\./dir")

- The path of each file or directory found during the descent is compared
against each pattern in turn (top to bottom) until a match is found.  Pattern
matching for that path then stops and the owner, group, dir_mode
& file_mode associated with the matching pattern are applied to the file or
directory, where appropriate (see below).

- A value of '-' for any or all of owner, group, dir_mode or file_mode
means that this attribute are to be un-altered when a match is found.

- A dir_mode or file_mode value of 0 (or any string which evaluates to zero
when converted to a number) is treated as a '-'

- file or dir mode must be specified in octal

- A pattern may match both files and directories, but dir_mode are only ever
applied to directories, and file_mode are only applied to files

=head1 OUTPUT

By default jperms.pl prints only a summary upon completion with the following
details:

- inspected: the number of objects (files or directories) inspected

- changed: the number of objects changed. Note: change of owner, group or mode,
or all three counts as a single change

- failed: the number of objects on which a changed failed. Note: failure to chmod or
chown (or both) counts as a single failure

- unchanged: the number of objects which don't need to be changed, i.e.
they already match the pattern rules

- pending: the number of objects which need to be changed, but weren't
either due to error or -no_run mode.

Other output is controlled by the -verbosity level:

  0 summary
  1 objects & changes needed
  2 all objects (even if no change required)
  3 commands used to make changes
  3 pattern rules
  4 pattern debug
  4 current perms
  4 target perms
  4 file
  4 perms debug

=head1 USERS AND GROUPS

- owners and groups must be specified as names; numeric ids
are not supported

- only users & groups which exist are allowed (i.e. in /etc/passwd or
/etc/group)

- specifying a user or group which does not exist will
cause an error message to be printed and the field
will have no effecte, i.e.  it will be treated as if it were '-'

- files found during the descent with numeric owner or group ids
(i.e. the user or group does not exist on the host), are treated
like any other file; i.e. the new ownership/group will be applied
as specified by a matching rule

=head1 COMMENTS

Lines starting with a '#' (optionally preceeded by whitespace)
are treated as comments and ignored.

=head1 EXAMPLE PATTERNS

Example pattern file:

  # pattern                      owner   group  dmode  fmode

  \./test/data.*/proj/cards      appuser grp2    770   -
  \./test/data.*/proj/r/r_import appuser grp2    770   -
  \./test/data.*/proj/outbound   appuser adm    2770   -
  \./test/data.*/proj/.*/inbox   appuser grp2    770   -
  \./test/data.*/proj/[^/]+      appuser grp2    750   -
  \./test/data[^/]*/proj         appuser adm     750   -
  \./test/data.*/tws/logs        appuser grp2    770   -
  \./test/data.*/tws             appuser grp2    750   -
  \./test/data.*/logs            appuser grp2    770   -
  \./test/data.*/scripts         root    adm     750   -
  \./test/data.*                 appuser grp2    770   660
  \./test/.*                     -       -       -     -
  \./test                        appuser appgrp  775   -

=head1 NOTES


